### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape-client-api#81]
Changes to ActiveModel::Dirty have broken compatibility with sequencescape-client-api this is due the use of ActiveModel::AttributeMutationTracker which assumes that @attibutes is a collection of rails attributes, not a simple hash. I tried a quick naive switch of @attributes out to @_attributes, but a few things started falling over, although this is probably the route we'll need to take, at least unless Rails make some changes.

**Comment by JamesGlover** [comment]
Looks like there may be a further issue with mutating hashed which are now frozen:
    FrozenError:
        can't modify frozen ActiveSupport::HashWithIndifferentAccess
      Shared Example Group: "it only allows creation from tubes" called from ./spec/models/labware_creators/tube_from_tube_spec.rb:27
      # /Users/jg16/projects/james/sequencescape-client-api/lib/sequencescape-api/resource/modifications.rb:41:in `clear'
      # /Users/jg16/projects/james/sequencescape-client-api/lib/sequencescape-api/resource/modifications.rb:41:in `initialize'
      # /Users/jg16/projects/james/sequencescape-client-api/lib/sequencescape-api/associations.rb:44:in `initialize'
      # /Users/jg16/projects/james/sequencescape-client-api/lib/sequencescape-api/resource.rb:31:in `initialize'
      # /Users/jg16/projects/james/sequencescape-client-api/lib/sequencescape-api/associations/base/instance_methods.rb:26:in `new'
      # /Users/jg16/projects/james/sequencescape-client-api/lib/sequencescape-api/associations/base/instance_methods.rb:26:in `new'
